# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb2f09b045bcc146ce8fa5976c4e4e16a14e872d55d89fdfd3993425bbed2c1a9086f7e2fc99e87c885c7473e818a07f6f33b12e5a717726f82afd0eff2c811c

test:
  secret_key_base: 36df847a9bfa5c8dc8828b3f628154238364efb7a7521a36628e8c5a94222cfd01c41c3afb6d3f4aaa76d12b77048276d81058b6618bd4dc20be7ccf9bcbf0f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
